[package]
name = "hspee/devinsdiner"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
t = "osyrisrblx/t@3.1.1"
Remo = "littensy/remo@1.5.2"
Signal = "sleitnick/signal@2.0.3"
Replica = "azutreo/replica@1.0.1"
Fusion = "elttob/fusion@0.3.0"
Lyra = "paradoxum-games/lyra@0.6.0"
TypedPromise = "howmanysmall/typed-promise@4.0.6"
Component = "sleitnick/component@2.4.8"
Janitor = "howmanysmall/janitor@1.18.3"
ZonePlus = "encrxyptedethan/zoneplus@3.2.0"

[server-dependencies]
cmdr = "evaera/cmdr@1.12.0"